### PR TITLE
Fix for ruptgen diags exception

### PR DESCRIPTION
**Pull request by chrisbc**
This solves an issue we have on a downstream integration test for filtered reports.
I think we should merge that feature upstream , but that can wait until after the big refactor.

### CODE REVIEW

**Comment by chrisbc** [comment]
@kevinmilner  this one gets all ours downstream tests passing in prep for repo consolidation on Friday. I'm hoping that this is the last from our forked repos, but will advise after @voj and I confer tomorrow.

**Comment by kevinmilner** [comment]
@chrisbc I'm all for catching the exception and agree that it shouldn't bring everything else down, but can you also let me know what the exception is so that I can see if there's a fix for the bug?

**Comment by chrisbc** [comment]
> @chrisbc I'm all for catching the exception and agree that it shouldn't bring everything else down, but can you also let me know what the exception is so that I can see if there's a fix for the bug?

Yes this is an awkward one as the 'failing' test is in our downstream repo. It happens when we filter the rupture sets for reporting purposes (see ) and I think relates to the much smaller range of data available. You could check out our repo and run those integration tests  to reproduce the problem,

SO option A)  is that we add this try/catch now. just so all our NZ test are passing. Then after everything has settled down I can push the filtered report feature upstream along with the failing test.

option B) is we disable our feature/test until I can patch on the new codebase. It's not mission critical but I was going to look at using it next week

(darn ctrl-enter works different in slack and GH comments) sorry about all the half--done comments - EOM :)

**Comment by kevinmilner** [comment]
@chrisbc I'll pull this in now, as I said I'm glad to catch it. It just implies that there's an exception possible somewhere in my current upstream code (that gets triggered by your small filtered rupture sets and not mine), so I was wondering if you could just let me know what that exception is so I can try to fix it so that it doesn't happen (rather than happens and gets caught).

I don't think we really want the fault-specific "filtered" rupture set page feature upstream right now -- I see the fault-specific pages as part of a separate (to-be-built) product.

**Comment by chrisbc** [comment]
@kevinmilner Thanks - yes I'll be happy to do some work on pinpointing the cause. The error I'm catching is this ......

```
java.lang.IllegalArgumentException: new max must be > min
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
	at org.opensha.commons.util.cpt.CPT.rescale(CPT.java:805)
	at org.opensha.sha.earthquake.faultSysSolution.ruptures.util.RupSetDiagnosticsPageGen.plotScalarMaxMapView(RupSetDiagnosticsPageGen.java:4727)
	at org.opensha.sha.earthquake.faultSysSolution.ruptures.util.RupSetDiagnosticsPageGen.generatePage(RupSetDiagnosticsPageGen.java:1425)
	at nz.cri.gns.NZSHM22.util.NZSHM22_InversionDiagnosticsReportBuilder.generateFilteredInversionDiagnosticsReport(NZSHM22_InversionDiagnosticsReportBuilder.java:57)
	at nz.cri.gns.NZSHM22.util.NZSHM22_InversionDiagnosticsReportBuilder_IntegrationTest.testRunReportForInversionSolution(NZSHM22_InversionDiagnosticsReportBuilder_IntegrationTest.java:63)
```

**Comment by kevinmilner** [comment]
Thanks, I just committed something that should fix that (98cb4ce). Will merge in now

**Pull request merged**
