### PR TITLE
Sliprate uncertainty constraint

### PR DESCRIPTION
**Pull request by chrisbc**
This adds the new SlipRateInversionConstraint class as conceived by MattG, including:

 - extend test coverage in the existing constraint test class
 - small mod to buildSmallTestRupSet() in FSS_ERF_ParamTest.java to produce some test data for above.
 - add as an option to enum SlipRateConstraintWeightingType, since this constraint is mutually exclusive with the others defined in the enum

### CODE REVIEW

**Comment by chrisbc** [comment]
@kevinmilner I thought I  had already raised this PR - sorry. Apologies there are some unsquashed commits here.

**Comment by kevinmilner** [comment]
@chrisbc how are you using the new enum entry? I don't see it used, but maybe it's in your codebase somewhere. If not critical I would leave that one out as that enum is likely to be abandoned as a U3-artifact, but I can be convinced otherwise.

**Comment by chrisbc** [comment]
> @chrisbc how are you using the new enum entry? I don't see it used, but maybe it's in your codebase somewhere. If not critical I would leave that one out as that enum is likely to be abandoned as a U3-artifact, but I can be convinced otherwise.

I'm using like so https://github.com/GNS-Science/nshm-nz-opensha/blob/c5613cb407f4e9844075b51c23bba1a459d4979a/src/main/java/nz/cri/gns/NZSHM22/opensha/inversion/NZSHM22_InversionInputGenerator.java#L138

I admit I was a bit hesitant to go this way, and I could have created a new enum just for this,  but since we're using the UCERF3 sliprate constraints and they're orthagonal to the new one I felt it was a nice concise setup. I suppose I should have added a test to -ucerf3 that demonstrated its use!

I can refactor this  and drop it from the commit if you think it's too messy.

**Comment by kevinmilner** [comment]
thanks for the info @chrisbc, I'll merge as is and we'll sort it out in the next cleaning stages

**Comment by chrisbc** [comment]
@kevinmilner thanks, that's a good plan. Meanwhile Oakley and I are getting our project and environments ready for the changes tomorrow.

**Pull request merged**
